name: Back Tests and Reports

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests and generate JaCoCo report
        run: mvn -B clean verify

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: Tests Reports
          path: back/target/site/jacoco
      



